FROM public.ecr.aws/lambda/python:3.10

COPY requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip3 install -r requirements.txt --target "${LAMBDA_TASK_ROOT}" -U --no-cache-dir

COPY serving/backend ${LAMBDA_TASK_ROOT}/serving/backend
COPY saved_models ${LAMBDA_TASK_ROOT}/saved_models

WORKDIR ${LAMBDA_TASK_ROOT}/serving/backend

CMD ["server.handler"]