FROM public.ecr.aws/lambda/python:3.10

COPY requirements.txt ${LAMBDA_TASK_ROOT}/requirements.txt
RUN pip install -r requirements.txt

COPY serving/backend ${LAMBDA_TASK_ROOT}
COPY saved_models ${LAMBDA_TASK_ROOT}/saved_models

CMD ["server.handler"]