FROM public.ecr.aws/lambda/python:3.10

COPY requirements.txt  ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt --target "${LAMBDA_TASK_ROOT}" -U --no-cache-dir

COPY serving/backend serving/backend
COPY saved_models saved_models

WORKDIR serving/backend

CMD ["server.handler"]