FROM python:3.10.0-slim

ENV TQDM_DISABLE=1

COPY requirements.txt .
COPY requirements_webserver.txt .
RUN pip install -r requirements.txt -r requirements_webserver.txt
RUN apt-get update && apt-get install -y libgomp1

COPY serving/backend .
COPY saved_models saved_models
COPY counterfactual_datasets/bestiaries_basic.csv  \
    counterfactual_datasets/
COPY training training

CMD ["uvicorn", "server:app", "--host", "0.0.0.0"]