FROM public.ecr.aws/lambda/python:3.10

RUN yum install libgomp git -y && \
    yum clean all -y && \
    rm -rf /var/cache/yum

COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install -r requirements.txt

COPY serving/backend ${LAMBDA_TASK_ROOT}
COPY saved_models ${LAMBDA_TASK_ROOT}/saved_models

CMD ["server.handler"]